require('packer_init')

require('core/options')
require('core/autocmds')
require('core/commands')
require('core/keymaps')
require('core/colors')
require('core/statusline')

require('plugins/tree')
require('plugins/indent-blankline')
require('plugins/treesitter')
require('plugins/alpha-nvim')
require('plugins/spectre')
require('plugins/bufferline')
require('plugins/refactoring')
require('plugins/zen-mode')
require('plugins/telescope')
require('plugins/prettier')
